name: py38_donghao
channels:
  - pytorch
  - defaults
dependencies:
  - abseil-cpp=20230802.0=h313beb8_2
  - absl-py=1.4.0=py38hca03da5_0
  - aiohttp=3.9.3=py38h80987f9_0
  - aiosignal=1.2.0=pyhd3eb1b0_0
  - async-timeout=4.0.3=py38hca03da5_0
  - attrs=23.1.0=py38hca03da5_0
  - blas=1.0=openblas
  - blinker=1.6.2=py38hca03da5_0
  - brotli=1.0.9=h1a28f6b_7
  - brotli-bin=1.0.9=h1a28f6b_7
  - brotli-python=1.0.9=py38hc377ac9_7
  - c-ares=1.19.1=h80987f9_0
  - ca-certificates=2024.3.11=hca03da5_0
  - cachetools=4.2.2=pyhd3eb1b0_0
  - certifi=2024.2.2=py38hca03da5_0
  - cffi=1.16.0=py38h80987f9_0
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - click=8.1.7=py38hca03da5_0
  - contourpy=1.0.5=py38h525c30c_0
  - cryptography=42.0.5=py38hd4332d6_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - filelock=3.13.1=py38hca03da5_0
  - fonttools=4.25.0=pyhd3eb1b0_0
  - freetype=2.12.1=h1192e45_0
  - frozenlist=1.4.0=py38h80987f9_0
  - gmp=6.2.1=hc377ac9_3
  - gmpy2=2.1.2=py38h8c48613_0
  - google-auth=2.6.0=pyhd3eb1b0_0
  - google-auth-oauthlib=0.5.2=py38hca03da5_0
  - grpc-cpp=1.48.2=hc60591f_4
  - grpcio=1.48.2=py38hc60591f_4
  - gtest=1.14.0=h48ca7d4_0
  - idna=3.4=py38hca03da5_0
  - importlib_resources=6.1.1=py38hca03da5_1
  - jinja2=3.1.3=py38hca03da5_0
  - jpeg=9e=h80987f9_1
  - kiwisolver=1.4.4=py38h313beb8_0
  - lcms2=2.12=hba8e193_0
  - lerc=3.0=hc377ac9_0
  - libbrotlicommon=1.0.9=h1a28f6b_7
  - libbrotlidec=1.0.9=h1a28f6b_7
  - libbrotlienc=1.0.9=h1a28f6b_7
  - libcxx=14.0.6=h848a8c0_0
  - libdeflate=1.17=h80987f9_1
  - libffi=3.4.4=hca03da5_0
  - libgfortran=5.0.0=11_3_0_hca03da5_28
  - libgfortran5=11.3.0=h009349e_28
  - libjpeg-turbo=2.0.0=h1a28f6b_0
  - libopenblas=0.3.21=h269037a_0
  - libpng=1.6.39=h80987f9_0
  - libprotobuf=3.20.3=h514c7bf_0
  - libtiff=4.5.1=h313beb8_0
  - libwebp-base=1.3.2=h80987f9_0
  - llvm-openmp=14.0.6=hc6e5704_0
  - lz4-c=1.9.4=h313beb8_0
  - markdown=3.4.1=py38hca03da5_0
  - markupsafe=2.1.3=py38h80987f9_0
  - matplotlib=3.7.2=py38hca03da5_0
  - matplotlib-base=3.7.2=py38h46d7db6_0
  - mpc=1.1.0=h8c48613_1
  - mpfr=4.0.2=h695f6f0_1
  - mpmath=1.3.0=py38hca03da5_0
  - multidict=6.0.4=py38h80987f9_0
  - munkres=1.1.4=py_0
  - ncurses=6.4=h313beb8_0
  - networkx=3.1=py38hca03da5_0
  - numpy=1.24.3=py38h1398885_0
  - numpy-base=1.24.3=py38h90707a3_0
  - oauthlib=3.2.2=py38hca03da5_0
  - openjpeg=2.3.0=h7a6adac_2
  - openssl=3.0.13=h1a28f6b_0
  - packaging=23.2=py38hca03da5_0
  - pillow=10.2.0=py38h80987f9_0
  - pip=23.3.1=py38hca03da5_0
  - pyasn1=0.4.8=pyhd3eb1b0_0
  - pyasn1-modules=0.2.8=py_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pyjwt=2.4.0=py38hca03da5_0
  - pyopenssl=24.0.0=py38hca03da5_0
  - pyparsing=3.0.9=py38hca03da5_0
  - pysocks=1.7.1=py38hca03da5_0
  - python=3.8.18=hb885b13_0
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - pytorch=2.2.1=py3.8_0
  - pytz=2023.3.post1=py38hca03da5_0
  - pyyaml=6.0.1=py38h80987f9_0
  - re2=2022.04.01=hc377ac9_0
  - readline=8.2=h1a28f6b_0
  - requests=2.31.0=py38hca03da5_1
  - requests-oauthlib=1.3.0=py_0
  - rsa=4.7.2=pyhd3eb1b0_1
  - setuptools=68.2.2=py38hca03da5_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.41.2=h80987f9_0
  - sympy=1.12=py38hca03da5_0
  - tensorboard=2.12.1=py38hca03da5_0
  - tensorboard-data-server=0.7.0=py38ha6e5c4f_0
  - tensorboard-plugin-wit=1.8.1=py38hca03da5_0
  - tk=8.6.12=hb8d0fd4_0
  - torchaudio=2.2.1=py38_cpu
  - torchvision=0.17.1=py38_cpu
  - tornado=6.3.3=py38h80987f9_0
  - tqdm=4.65.0=py38h86d0a89_0
  - typing_extensions=4.9.0=py38hca03da5_1
  - urllib3=2.1.0=py38hca03da5_1
  - werkzeug=2.3.8=py38hca03da5_0
  - wheel=0.41.2=py38hca03da5_0
  - xz=5.4.6=h80987f9_0
  - yaml=0.2.5=h1a28f6b_0
  - yarl=1.9.3=py38h80987f9_0
  - zlib=1.2.13=h5a0b063_0
  - zstd=1.5.5=hd90d995_0
  - pip:
      - appdirs==1.4.4
      - cloudpickle==3.0.0
      - docker-pycreds==0.4.0
      - farama-notifications==0.0.4
      - gitdb==4.0.11
      - gitpython==3.1.42
      - gym==0.26.2
      - gym-notices==0.0.8
      - gymnasium==0.29.1
      - importlib-metadata==7.0.2
      - pettingzoo==1.24.3
      - protobuf==4.25.3
      - psutil==5.9.8
      - pygame==2.5.2
      - pymunk==6.6.0
      - sentry-sdk==1.42.0
      - setproctitle==1.3.3
      - smmap==5.0.1
      - supersuit==3.9.2
      - tinyscaler==1.2.7
      - wandb==0.16.4
      - zipp==3.18.1
prefix: /Users/hyunin/anaconda3/envs/py38_donghao
